name: Make a GitHub Release

on:
  push:
    tags:
      - 'v**'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR file
        run: mvn package

      - name: Create GitHub Release and Upload JAR Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
